src/Makefile.am: fix linking with log4cpp
linknx fails to build with log4cpp because LOG4CPP_CFLAGS (which
contains -pthread) is added to AM_CPPFLAGS (which is not used at link
time) instead of AM_CXXFLAGS:

/home/buildroot/autobuild/instance-0/output/host/bin/mipsel-linux-g++  -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os     -o linknx linknx.o logger.o ruleserver.o objectcontroller.o eibclient.o threads.o timermanager.o persistentstorage.o xmlserver.o smsgateway.o emailgateway.o knxconnection.o services.o suncalc.o luacondition.o ioport.o ../ticpp/libticpp.a  -L/home/buildroot/autobuild/instance-0/output/host/mipsel-buildroot-linux-gnu/sysroot/usr/bin/../../usr/lib -lpthsem  -L/home/buildroot/autobuild/instance-0/output/host/bin/../mipsel-buildroot-linux-gnu/sysroot/usr/lib -llog4cpp     -lm
/home/buildroot/autobuild/instance-0/output/host/mipsel-buildroot-linux-gnu/sysroot/usr/bin/../../usr/lib/liblog4cpp.so: undefined reference to `pthread_key_create'

So move LOG4CPP_CFLAGS to AM_CXXFLAGS

Fixes:
 - http://autobuild.buildroot.org/results/1863f8f27041bc15ca68e786ba3b8e4764c40574

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>