src/suncalc.cpp: fix build with gcc 6.x
src/suncalc.cpp currently includes <math.h>, but this causes a build
failure with gcc 6.x, and <cmath> should be used instead. The build
failure is:

/home/test/autobuild/run/instance-0/output/host/usr/arc-buildroot-linux-uclibc/include/c++/6.1.1/cmath:101:37: error: '__is_integer' was not declared in this scope
     typename __gnu_cxx::__enable_if<__is_integer<_Tp>::__value,
                                     ^~~~~~~~~~~~

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>